# Azure CLI login by using OpenID Connect (OIDC) https://github.com/Azure/login
# Azure AD Workload Identity Federation https://www.youtube.com/watch?v=u7PcV9ivaAo

name: Run Azure Login with OIDC
#on: [push]
on: [workflow_dispatch] # run action manually on deamand

# important to add permissions to avoid Error: Please make sure to give write permissions to id-token in the workflow.
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Azure login 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # enable PowerShell if one of your steps will be excecuting ps script like step "Azure PowerShell script" Get-AzResourceGroup
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzResourceGroup
